travis:
  secure:
    BINSTAR_TOKEN: c5aK5awcTrf2f+neSULjp44jXEIYSL3UwgEfVSYRYP1wdVqfRp9nzbqIYuBJKHBNGl9qPUNTliIyn8b17QeGF9QYBOLfTm/KDN5hkdYwoKwzbXraLlr+GUVnpp7HsFeFFGo1HLBVKjwBurxyiE4QmATFkzG5CTjWhi+du98Lr1Et9j/OkZ4h+y728fObOlJw93sG33cQ7yBk7evZK/2tHAJrfHfRnLGV5PT6SXAIUotlbZv4MJlszOxDSb6iuw4mH7il+pjeC/th0wUHmss+ov9Q1/9GKtOmljRU+qaL96kthAwBi0n0p2ZPuXOzw1hMGYtM6WQNmLkJhNg5j+KuO/BSNLUh77hyHMK6e0O/Yb8kHnMoa9Q0HKSWECBZabqQaKdcP7yLN506Uy5r0hptUeU1PV1MxVuMTAbXaL2kJ3ieSOjrsb03BZWK/+Num9QN8DBS3A/y8BlkuGc3i9VnDzd7iUfEt97PEmreeBmxGLcFIH+oG9PQbFIeEJOY3OGLnYCzZZwqzCKvyLnLhBYCQZePcXyZssem9WKGdKYhTB8zjjpseXf/O9ir0uMG9FV+ey8A9llzR9/rzbHOZFNZeCWpjk/6COFIoJtcD0dTXsRRfy8Fn/TXIm2gbQ2SoCzsuBhttHp8SUKxfsbxLf1/8Hn8Jv1e7F5TZH8XtSGGRA8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
